// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyuTmyw7adLEmcNlYhipYFtKKvVYWq1zM',
    appId: '1:223908772884:web:4b48419ce202d983983b01',
    messagingSenderId: '223908772884',
    projectId: 'create-doc-8c600',
    authDomain: 'create-doc-8c600.firebaseapp.com',
    storageBucket: 'create-doc-8c600.appspot.com',
    measurementId: 'G-HQJSCS8Y7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn1Tdx2w3-Bogj3Vm2iTnG8eufJsINqXY',
    appId: '1:223908772884:android:0d7df6d10377f462983b01',
    messagingSenderId: '223908772884',
    projectId: 'create-doc-8c600',
    storageBucket: 'create-doc-8c600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEFbHe4um5QIVdHxvB4DV-bFgzwMUdKzU',
    appId: '1:223908772884:ios:e573b9b64d4ad62c983b01',
    messagingSenderId: '223908772884',
    projectId: 'create-doc-8c600',
    storageBucket: 'create-doc-8c600.appspot.com',
    iosBundleId: 'com.app.create-doc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEFbHe4um5QIVdHxvB4DV-bFgzwMUdKzU',
    appId: '1:223908772884:ios:4a3c6fdf3faa6180983b01',
    messagingSenderId: '223908772884',
    projectId: 'create-doc-8c600',
    storageBucket: 'create-doc-8c600.appspot.com',
    iosBundleId: 'com.app.createProject.RunnerTests',
  );
}
